# 语法参考： https://aliyuque.antfin.com/aoneci/gncflv/zn9dhevbwby6715s
name: Nodejs单元测试

triggers:
  push:
    branches:
      - 'daily/**'
  merge_request:
    target-branches:
      - '**'

jobs:
  test-job:
    image: alios-8u
    steps:
      - uses: checkout
      - uses: setup-env
        inputs:
          node-version: 20
          tnpm-version: 9
          tnpm-cache: false
      - run: |
          tnpm i
          npm ls
          npm run build
          npm run format
          IT_CONFIG=${{vars.IT_CONFIG}} npm run cov:node
          cp -rf coverage/node/* coverage/
      - uses: nodejs-coverage
