ELECTRON_BUILDER_BINARIES_MIRROR=https://npm.taobao.org/mirrors/electron-builder-binaries/
ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/ 

i:
	ELECTRON_MIRROR=$(ELECTRON_MIRROR) ELECTRON_BUILDER_BINARIES_MIRROR=$(ELECTRON_BUILDER_BINARIES_MIRROR) npm i
run:
	npm start
	